# tasks for Debian Familly
---

- name: repository installation
  apt:
    deb: "{{ xtradb_repo_packages }}"

- name: Replace the "{{ xtradb_repo_file_path }}"
  replace:
    path: "{{ xtradb_repo_file_path }}"
    regexp: "{{ xtradb_deb_repo_url }}"
    replace: "{{ xtradb_repo_url }}"

- name: update cache
  apt:
    update_cache: yes
  changed_when: false

...
