# tasks for Red Hat Familly
---

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status == 'enabled'

- name: Replace the "{{ xtradb_repo_file_path }}"
  replace:
    path: "{{ xtradb_repo_file_path }}"
    regexp: "{{ xtradb_yum_repo_url }}"
    replace: "{{ xtradb_repo_url }}"

- name: repository installation
  yum:
    name: "{{ xtradb_repo_packages }}"
    state: present

...
